# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: "true"
  branches:
    include:
      - master
  paths:
    exclude:
      - README.md
      - azure-pipelines.yml
pr:
  autoCancel: "true"
  branches:
    include:
      - master
  paths:
    exclude:
      - README.md
jobs:
- job: ProdDeploy
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  -bash:
	sudo apt-get update  
	sudo apt-get install default-jre  
	sudo apt-get install default-jdk
	displayName: JDk

- bash:
	wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
	mkdir sfdx
	tar xJf sfdx-linux-amd64.tar.xz -C sfdx --strip-components 1
	./sfdx/install
	displayName: CLI test
    - bash: 
        sfdx force:auth:jwt:grant --clientid $(salesforceProdClientid) --jwtkeyfile ./buildfiles/server.key --username $(salesforceProdUsername) --instanceurl $(salesforceProdInstanceUrl) -a prod
      displayName: Authorize salesforce org
 
    - bash: 
        sfdx force:source:deploy -u prod -p force-app/main/default
      displayName: Deploy source code to Production
